#!/bin/sh
source scrapyvirtualenv/expresspros/expressprosDemoShell.sh
source scrapyvirtualenv/expresspros/stackoverflowDemoShell.sh
source scrapyvirtualenv/expresspros/jobsupsDemoShell.sh
source scrapyvirtualenv/expresspros/targetedjobfairsDemoShell.sh
